# escape=`
FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Debug -o out


FROM microsoft/dotnet:2.1-runtime-nanoserver-1809

ARG VS_REMOTE_DEBUGGER_PATH
ARG VS_OUT_DIR

ADD $VS_REMOTE_DEBUGGER_PATH "c:\windows"


WORKDIR /app
COPY --from=build-env /app/out ./

ENTRYPOINT ["dotnet", "filtermodule.dll"]